import aff1 from "../../assets_affirmation/affirmation1.mp4"
import aff2 from "../../assets_affirmation/affirmation2.mp4"
import aff3 from "../../assets_affirmation/affirmation3.mp4"
import aff4 from "../../assets_affirmation/affirmation4.mp4"
import aff5 from "../../assets_affirmation/affirmation5.mp4"
import aff6 from "../../assets_affirmation/affirmation6.mp4"
import aff7 from "../../assets_affirmation/affirmation7.mp4"
import aff8 from "../../assets_affirmation/affirmation8.mp4"
import aff9 from "../../assets_affirmation/affirmation9.mp4"
import aff10 from "../../assets_affirmation/affirmation10.mp4"

export const affirm_data = [
    {
        id: 1,
        videoFile: aff1,
        rusQuestion: "1",
        before: false,
        border: false,
        engDescription: "Я благодарен за множество благословений в моей жизни",
        answer: "I am grateful for the many blessings in my life",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 6000,
        
    },
    {
        id: 2,
        videoFile: aff2,
        rusQuestion: "2",
        before: false,
        border: false,
        engDescription: "сегодня я ищу и ценю хорошее",
        answer: "today I look for and appreciate the good",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 6000,
    },
    {
        id: 3,
        videoFile: aff3,
        rusQuestion: "3",
        before: false,
        border: false,
        engDescription: "Я приветствую радость в своей жизни",
        answer: "I welcome joy into my life",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 6000,
    },
    {
        id: 4,
        videoFile: aff4,
        rusQuestion: "4",
        before: false,
        border: false,
        engDescription: "Я нахожусь в гармонии с изобильной природой Вселенной",
        answer: "I am in tune with the abundant nature of the universe",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 6000,
    },
    {
        id: 5,
        videoFile: aff5,
        rusQuestion: "5",
        before: false,
        border: false,
        engDescription: "деньги приходят ко мне ожидаемым и неожиданным образом",
        answer: "money comes to me in expected and unexpected ways",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 6000,
    },
    {
        id: 6,
        videoFile: aff6,
        rusQuestion: "6",
        before: false,
        border: false,
        engDescription: "мое тело знает, что лучше для моего здоровья и благополучия",
        answer: "my body knows what's best for my health and well-being",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 6000,
    },
    {
        id: 7,
        videoFile: aff7,
        rusQuestion: "7",
        before: false,
        border: false,
        engDescription: "Я привлекаю идеальных людей в нужное время",
        answer: "I attract the perfect people at the right time",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 6000,
    },
    {
        id: 8,
        videoFile: aff8,
        rusQuestion: "8",
        before: false,
        border: false,
        engDescription: "Я заслуживаю счастья и успеха",
        answer: "I deserve happiness and success",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 6000,
    },
    {
        id: 9,
        videoFile: aff9,
        rusQuestion: "9",
        before: false,
        border: false,
        engDescription: "что-то чудесное всегда вот-вот произойдет",
        answer: "something wonderful is always on the verge of happening",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 6000,
    },
    {
        id: 10,
        videoFile: aff10,
        rusQuestion: "10",
        before: false,
        border: false,
        engDescription: "Я достоен . меня достаточно",
        answer: "I am worthy. I am enough.",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 6000,
    },
]