import aff1 from "../../assets_affirmation/affirmation1.mp4"
import aff2 from "../../assets_affirmation/affirmation2.mp4"
import aff3 from "../../assets_affirmation/affirmation3.mp4"
import aff4 from "../../assets_affirmation/affirmation4.mp4"
import aff5 from "../../assets_affirmation/affirmation5.mp4"
import aff6 from "../../assets_affirmation/affirmation6.mp4"
import aff7 from "../../assets_affirmation/affirmation7.mp4"
import aff8 from "../../assets_affirmation/affirmation8.mp4"
import aff9 from "../../assets_affirmation/affirmation9.mp4"
import aff10 from "../../assets_affirmation/affirmation10.mp4"

export const affirm_data = [
    {
        id: 1,
        videoFile: aff1,
        rusQuestion: "1",
        before: false,
        border: false,
        engDescription: "Я денежный магнит",
        answer: "I am a money magnet",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 18000,
        
    },
    {
        id: 2,
        videoFile: aff2,
        rusQuestion: "2",
        before: false,
        border: false,
        engDescription: "Я всегда привлекаю изобилие",
        answer: "I am always attracting abundance",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 23000,
    },
    {
        id: 3,
        videoFile: aff3,
        rusQuestion: "3",
        before: false,
        border: false,
        engDescription: "Я получаю деньги постоянно",
        answer: "I am receiving money at all times",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 24000,
    },
    {
        id: 4,
        videoFile: aff4,
        rusQuestion: "4",
        before: false,
        border: false,
        engDescription: "Я богат",
        answer: "I am wealthy",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 17000,
    },
    {
        id: 5,
        videoFile: aff5,
        rusQuestion: "5",
        before: false,
        border: false,
        engDescription: "Я открыт и готов получать деньги любыми способами",
        answer: "I am open and willing to receive money in all ways",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        timeGo: 29000,
    },
    {
        id: 6,
        videoFile: aff6,
        rusQuestion: "6",
        before: false,
        border: false,
        engDescription: "У меня их всегда более чем достаточно",
        answer: "I always have more than enough",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        try: 1,
        timeGo: 23000,
    },
    {
        id: 7,
        videoFile: aff7,
        rusQuestion: "7",
        before: false,
        border: false,
        engDescription: "Я привлекаю все больше и больше денег",
        answer: "I attract more money and more money",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        try: 1,
        timeGo: 28000,
    },
    {
        id: 8,
        videoFile: aff8,
        rusQuestion: "8",
        before: false,
        border: false,
        engDescription: "Я использую свои деньги для своего высшего блага и блага других",
        answer: "I use my money for my highest good and the good of others",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        try: 1,
        timeGo: 28000,
    },
    {
        id: 9,
        videoFile: aff9,
        rusQuestion: "9",
        before: false,
        border: false,
        engDescription: "Я в гармонии с изобилием",
        answer: "I am in alinement with the abundance",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        try: 1,
        timeGo: 21000,
    },
    {
        id: 10,
        videoFile: aff10,
        rusQuestion: "10",
        before: false,
        border: false,
        engDescription: "я финансово свободен",
        answer: "I am financially free",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
        try: 1,
        timeGo: 23000,
    },
]