import video1 from "../../assets/video1.mp4"
import video2 from "../../assets/video2.mp4"
import video3 from "../../assets/video3.mp4"

 export const new_data = [
    {
        id: 200,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 199,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 198,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 197,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 196,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 195,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 194,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 193,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 192,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 191,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 190,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 189,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 188,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 187,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 186,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 185,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 184,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 183,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 182,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 181,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 180,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 179,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 178,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 177,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 176,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 175,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 174,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 173,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 172,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 171,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 170,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 169,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 168,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 167,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 166,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 165,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 164,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 163,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 162,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 161,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 160,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 159,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 158,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 157,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 156,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 155,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 154,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 153,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 152,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 151,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 150,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 149,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 148,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 147,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 146,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 145,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 144,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 143,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 142,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 141,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 140,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 139,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 138,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 137,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 136,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 135,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 134,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 133,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 132,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 131,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 130,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 129,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 128,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 127,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 126,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 125,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 124,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 123,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 122,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 121,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 120,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 119,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 118,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 117,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 116,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 115,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 114,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 113,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 112,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 111,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 110,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 109,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 108,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 107,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 106,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 105,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 104,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 103,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 102,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 101,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 100,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 99,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 98,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 97,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 96,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 95,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 94,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 93,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 92,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 91,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 80,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 89,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 88,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 87,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 86,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 85,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 84,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 83,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 82,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 81,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 80,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 79,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 78,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 77,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 76,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 75,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 74,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 73,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 72,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 71,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 70,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 69,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 68,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 67,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 66,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 65,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 64,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 63,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 62,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 61,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 60,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 59,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 58,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 57,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 56,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 55,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 54,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 53,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 52,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 51,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 50,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 49,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 48,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 47,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 46,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 45,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 44,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 43,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 42,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 41,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 40,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 39,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 38,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 37,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 36,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 35,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 34,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 33,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 32,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 31,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 30,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 29,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 28,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 27,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 26,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 25,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 24,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 23,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 22,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 21,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 20,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 19,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 18,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 17,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 16,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 15,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 14,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 13,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 12,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 11,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 10,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 9,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 8,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 7,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 6,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 5,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 4,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 3,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 2,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 1,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    }
]
