import video1 from "../../assets/video1.mp4"
import video2 from "../../assets/video2.mp4"
import video3 from "../../assets/video3.mp4"
import video4 from "../../assets/video4.mp4"
import video5 from "../../assets/video5.mp4"
import video6 from "../../assets/video6.mp4"
import video7 from "../../assets/video7.mp4"
import video8 from "../../assets/video8.mp4"
import video9 from "../../assets/video9.mp4"
import video10 from "../../assets/video10.mp4"
import video11 from "../../assets/video11.mp4"
import video12 from "../../assets/video12.mp4"
import video13 from "../../assets/video13.mp4"
import video14 from "../../assets/video14.mp4"
import video15 from "../../assets/video15.mp4"
import video16 from "../../assets/video16.mp4"
import video17 from "../../assets/video17.mp4"
import video18 from "../../assets/video18.mp4"
import video19 from "../../assets/video19.mp4"
import video20 from "../../assets/video20.mp4"
import video21 from "../../assets/video21.mp4"
import video22 from "../../assets/video22.mp4"
import video23 from "../../assets/video23.mp4"
import video24 from "../../assets/video24.mp4"
import video25 from "../../assets/video25.mp4"
import video26 from "../../assets/video26.mp4"
import video27 from "../../assets/video27.mp4"
import video28 from "../../assets/video28.mp4"
import video29 from "../../assets/video29.mp4"
import video30 from "../../assets/video30.mp4"
import video31 from "../../assets/video31.mp4"
import video32 from "../../assets/video32.mp4"
import video33 from "../../assets/video33.mp4"
import video34 from "../../assets/video34.mp4"
import video35 from "../../assets/video35.mp4"
import video36 from "../../assets/video36.mp4"
import video37 from "../../assets/video37.mp4"
import video38 from "../../assets/video38.mp4"
import video39 from "../../assets/video39.mp4"
import video40 from "../../assets/video40.mp4"
import video41 from "../../assets/video41.mp4"
import video42 from "../../assets/video42.mp4"
import video43 from "../../assets/video43.mp4"
import video44 from "../../assets/video44.mp4"
import video45 from "../../assets/video45.mp4"
import video46 from "../../assets/video46.mp4"
import video47 from "../../assets/video47.mp4"
import video48 from "../../assets/video48.mp4"
import video49 from "../../assets/video49.mp4"
import video50 from "../../assets/video50.mp4"
import video51 from "../../assets/video51.mp4"
import video52 from "../../assets/video52.mp4"
import video53 from "../../assets/video53.mp4"
import video54 from "../../assets/video54.mp4"
import video55 from "../../assets/video55.mp4"
import video56 from "../../assets/video56.mp4"
import video57 from "../../assets/video57.mp4"
import video58 from "../../assets/video58.mp4"
import video59 from "../../assets/video59.mp4"
import video60 from "../../assets/video60.mp4"
import video61 from "../../assets/video61.mp4"
import video62 from "../../assets/video62.mp4"
import video63 from "../../assets/video63.mp4"
import video64 from "../../assets/video64.mp4"
import video65 from "../../assets/video65.mp4"
import video66 from "../../assets/video66.mp4"


 export const new_data = [
    {
        id: 269,
        videoFile: video66,
        rusQuestion: "придумывание",
        before: false,
        border: false,
        engDescription: "to make something, usually food, by adding several different parts together, often in a way that is original or not planned: also to make something new from different things:",
        answer: "concocting",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 268,
        videoFile: video65,
        rusQuestion: "обувь",
        before: false,
        border: false,
        engDescription: "shoes, boots, or any other outer covering for the human foot:",
        answer: "footwear",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 267,
        videoFile: video64,
        rusQuestion: "похоть , страсть",
        before: false,
        border: false,
        engDescription: "a very strong sexual desire:",
        answer: "lust",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 266,
        videoFile: video63,
        rusQuestion: "капля",
        before: false,
        border: false,
        engDescription: "a small round-shaped amount of liquid:",
        answer: "drop",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 265,
        videoFile: video62,
        rusQuestion: "щепотка",
        before: false,
        border: false,
        engDescription: "a small amount of something, such as a powder, especially the amount that a person can hold between their first finger and thumb:",
        answer: "pinch",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 264,
        videoFile: video61,
        rusQuestion: "капризный",
        before: false,
        border: false,
        engDescription: "When children are oooooo, or their behaviour is oooooo, they behave badly or do not do what they are told to do:",
        answer: "naughty",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 263,
        videoFile: video60,
        rusQuestion: "угнетенный",
        before: false,
        border: false,
        engDescription: "governed in an unfair and cruel way and prevented from having opportunities and freedom:",
        answer: "oppressed",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 262,
        videoFile: video60,
        rusQuestion: "униженный",
        before: false,
        border: false,
        engDescription: "to cause people to feel that they or other people have no value and do not have the respect or good opinion of others:",
        answer: "degraded",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 261,
        videoFile: video59,
        rusQuestion: "союз",
        before: false,
        border: false,
        engDescription: "an organization that represents the people who work in a particular industry, protects their rights and may agree pay, working conditions, etc. with their employers:",
        answer: "union",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 260,
        videoFile: video58,
        rusQuestion: "зайти , заглянуть",
        before: false,
        border: false,
        engDescription: "to visit briefly:",
        answer: "pop in",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 259,
        videoFile: video57,
        rusQuestion: "зелья",
        before: false,
        border: false,
        engDescription: "a liquid that is believed to have a magical effect on someone who drinks it:",
        answer: "potion",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 258,
        videoFile: video57,
        rusQuestion: "заклинания",
        before: false,
        border: false,
        engDescription: "an evil spell, bringing bad luck and trouble:",
        answer: "hex",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 257,
        videoFile: video56,
        rusQuestion: "изба",
        before: false,
        border: false,
        engDescription: "a small house, usually in the countryside:",
        answer: "cottage",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 256,
        videoFile: video55,
        rusQuestion: "выкатить приветственный вагон",
        before: false,
        border: false,
        engDescription: "used to refer to a happy and friendly way of greeting people who are new to a place:",
        answer: "roll out the welcome wagon",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 255,
        videoFile: video54,
        rusQuestion: "изысканный",
        before: false,
        border: false,
        engDescription: "very beautiful and delicate: especially beautiful or admirable:",
        answer: "exquisite",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 254,
        videoFile: video54,
        rusQuestion: "блюдо",
        before: false,
        border: false,
        engDescription: "food prepared in a particular way as part of a meal:  a container, flatter than a bowl and sometimes with a lid, from which food can be served or which can be used for cooking:",
        answer: "dish",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 253,
        videoFile: video53,
        rusQuestion: "праздничный",
        before: false,
        border: false,
        engDescription: "having or producing happy and enjoyable feelings suitable for a festival or other special occasion:",
        answer: "festive",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 252,
        videoFile: video52,
        rusQuestion: "расслабляться",
        before: false,
        border: false,
        engDescription: "to become more relaxed and less serious:",
        answer: "lighten up",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 251,
        videoFile: video51,
        rusQuestion: "пощажен",
        before: false,
        border: false,
        engDescription: "If something is spare, it is available to use because it is extra: to not hurt or destroy something or someone:",
        answer: "spared",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 250,
        videoFile: video50,
        rusQuestion: "обязан",
        before: false,
        border: false,
        engDescription: "to be forced to do something or feel that you must do something:",
        answer: "obliged",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 249,
        videoFile: video50,
        rusQuestion: "сопровождать",
        before: false,
        border: false,
        engDescription: "to go with someone or to be provided or exist at the same time as something:  to go with someone or to exist at the same time as something:",
        answer: "accompany",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 248,
        videoFile: video49,
        rusQuestion: "неправильно судить",
        before: false,
        border: false,
        engDescription: "to form an opinion or idea about someone or something that is unfair or wrong:",
        answer: "misjudge",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 247,
        videoFile: video48,
        rusQuestion: "бобы",
        before: false,
        border: false,
        engDescription: "a seed, or the pod containing seeds, of various climbing plants, eaten as a vegetable:",
        answer: "beans",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 246,
        videoFile: video47,
        rusQuestion: "помет",
        before: false,
        border: false,
        engDescription: "a group of animals that are born at the same time and have the same mother:   small pieces of rubbish that have been left lying on the ground in public places:",
        answer: "litter",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 245,
        videoFile: video46,
        rusQuestion: "умолять",
        before: false,
        border: false,
        engDescription: "to ask someone to do or not do something in a very sincere, emotional, and determined way:",
        answer: "implore",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 244,
        videoFile: video45,
        rusQuestion: "кастрировать",
        before: false,
        border: false,
        engDescription: "to remove part of an animal's sexual organs, so that it cannot produce young animals:",
        answer: "neuter",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 243,
        videoFile: video44,
        rusQuestion: "орудие",
        before: false,
        border: false,
        engDescription: "a gun: or weapon:",
        answer: "piece",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 242,
        videoFile: video43,
        rusQuestion: "мурлыкать",
        before: false,
        border: false,
        engDescription: "to make a quiet, continuous, soft sound:  (of a cat) to make a soft, low, continuous sound",
        answer: "purr",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 241,
        videoFile: video42,
        rusQuestion: "связь , узы",
        before: false,
        border: false,
        engDescription: "to develop a close connection or strong relationship with someone, or to make someone do this:  to stick materials together, especially using glue, or to be stuck together like this:  a close connection joining two or more people:",
        answer: "bond",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 240,
        videoFile: video41,
        rusQuestion: "обидчивый",
        before: false,
        border: false,
        engDescription: "angry and offended:",
        answer: "huffy",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 239,
        videoFile: video40,
        rusQuestion: "зловещий",
        before: false,
        border: false,
        engDescription: "making you feel that something bad or evil might happen:  evil, or suggesting that something evil is going to happen:",
        answer: "sinister",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 238,
        videoFile: video39,
        rusQuestion: "подлый , презренный",
        before: false,
        border: false,
        engDescription: "very unpleasant or bad, causing strong feelings of dislike:",
        answer: "sdespicable",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 237,
        videoFile: video38,
        rusQuestion: "пижамную вечеринку",
        before: false,
        border: false,
        engDescription: "a party when a group of children spend the night at one child's house",
        answer: "slumber party",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 236,
        videoFile: video37,
        rusQuestion: "подсказать тебе",
        before: false,
        border: false,
        engDescription: "to give someone information that is necessary or new:",
        answer: "clue you in",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 235,
        videoFile: video36,
        rusQuestion: "майонез",
        before: false,
        border: false,
        engDescription: "informal for mayonnaise :",
        answer: "mayo",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 234,
        videoFile: video35,
        rusQuestion: "сонный",
        before: false,
        border: false,
        engDescription: "being in a state between sleeping and being awake:",
        answer: "drowsy",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 233,
        videoFile: video34,
        rusQuestion: "гладкий",
        before: false,
        border: false,
        engDescription: "to make something perfectly flat or regular: having a surface or consisting of a substance that is perfectly regular and has no holes, lumps, or areas that rise or fall suddenly:",
        answer: "smooth",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 232,
        videoFile: video33,
        rusQuestion: "туфли-лодочки",
        before: false,
        border: false,
        engDescription: "a type of flat shoe, like a ballet dancer's shoe, worn by women",
        answer: "pumps",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 231,
        videoFile: video32,
        rusQuestion: "легким движением запястья , резкое движение",
        before: false,
        border: false,
        engDescription: "a song by the British rock band Queen",
        answer: "flick of the wrist",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 230,
        videoFile: video31,
        rusQuestion: "палочка",
        before: false,
        border: false,
        engDescription: "a special thin stick waved by a person who is performing magic tricks:",
        answer: "wand",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 229,
        videoFile: video30,
        rusQuestion: "сладкий горох",
        before: false,
        border: false,
        engDescription: "a climbing plant with sweet-smelling flowers that are often a pale colour",
        answer: "sweet pea",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 228,
        videoFile: video29,
        rusQuestion: "лекарство",
        before: false,
        border: false,
        engDescription: "a successful way of curing an illness or dealing with a problem or difficulty:",
        answer: "remedy",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 227,
        videoFile: video28,
        rusQuestion: "животики",
        before: false,
        border: false,
        engDescription: "the stomach, or the lower front part of the body:",
        answer: "tummies",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 226,
        videoFile: video27,
        rusQuestion: "очарованный",
        before: false,
        border: false,
        engDescription: "affected by magic or seeming to be affected by magic:",
        answer: "enchanted",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
     {
        id: 225,
        videoFile: video26,
        rusQuestion: "чертовски",
        before: false,
        border: false,
        engDescription: "used instead of damn to express anger:",
        answer: "darn",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 224,
        videoFile: video25,
        rusQuestion: "бортовое",
        before: false,
        border: false,
        engDescription: "happening or available during a flight:",
        answer: "in-flight",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 223,
        videoFile: video24,
        rusQuestion: "незрелый",
        before: false,
        border: false,
        engDescription: "not behaving in a way that is as calm and wise as people expect from someone of your age:",
        answer: "immature",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 222,
        videoFile: video23,
        rusQuestion: "попасть в пробку",
        before: false,
        border: false,
        engDescription: "the expression means that in the course of your journey you encountered congestion and delays as the road was very busy with other road users.",
        answer: "hit traffic",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 221,
        videoFile: video22,
        rusQuestion: "Для тебя есть мелкий шрифт",
        before: false,
        border: false,
        engDescription: "The term usually refers to the small text in contracts that people typically sign when signing up for something",
        answer: "there's some fine print for you",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 220,
        videoFile: video21,
        rusQuestion: "напыщенный",
        before: false,
        border: false,
        engDescription: "too serious and full of importance: feeling or showing that you think you are better or more important than other people:",
        answer: "pompous",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 219,
        videoFile: video20,
        rusQuestion: "Загородный клуб",
        before: false,
        border: false,
        engDescription: "a sports or social organization based in the countryside, often one that only allows people to become members if they have enough money or a high social position",
        answer: "country club",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 218,
        videoFile: video19,
        rusQuestion: "он же",
        before: false,
        border: false,
        engDescription: "abbreviation for also known as: used when someone has another name:",
        answer: "aka",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 217,
        videoFile: video19,
        rusQuestion: "он же",
        before: false,
        border: false,
        engDescription: "abbreviation for also known as: used when someone has another name:",
        answer: "aka",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 216,
        videoFile: video18,
        rusQuestion: "бал",
        before: false,
        border: false,
        engDescription: "a large, formal occasion where people dance",
        answer: "ball",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 215,
        videoFile: video17,
        rusQuestion: "настоящим , сим",
        before: false,
        border: false,
        engDescription: "with these words or with this action:  by this statement, action, or law:",
        answer: "hereby",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 214,
        videoFile: video17,
        rusQuestion: "вызванный",
        before: false,
        border: false,
        engDescription: "an official demand to appear in a court of law:   an order to come and see someone:  to order someone to come to a person or place:",
        answer: "summoned",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 213,
        videoFile: video16,
        rusQuestion: "подлый , мошеннически",
        before: false,
        border: false,
        engDescription: "used to describe people or behaviour that you disapprove of but still like:",
        answer: "rascally",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 212,
        videoFile: video15,
        rusQuestion: "приятное зрелище, больной , болячка , Взгляд усталых глаз",
        before: false,
        border: false,
        engDescription: "a way of saying that you are very pleased to see someone or that you think someone is very attractive:",
        answer: "a sight for sore eyes",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 211,
        videoFile: video14,
        rusQuestion: "петь",
        before: false,
        border: false,
        engDescription: "to sing or play a musical instrument very loudly:",
        answer: "belting out",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 210,
        videoFile: video13,
        rusQuestion: "излечивать",
        before: false,
        border: false,
        engDescription: "to make someone with an illness healthy again:",
        answer: "cure",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 209,
        videoFile: video12,
        rusQuestion: "паутинка",
        before: false,
        border: false,
        engDescription: "the very thin thread that spiders produce to make webs",
        answer: "gossamer",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 208,
        videoFile: video11,
        rusQuestion: "страшное",
        before: false,
        border: false,
        engDescription: "causing fear or worry:",
        answer: "dreaded",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 207,
        videoFile: video10,
        rusQuestion: "конечность",
        before: false,
        border: false,
        engDescription: "an arm or leg of a person or animal:",
        answer: "limb",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 206,
        videoFile: video9,
        rusQuestion: "палящий , обжигающий",
        before: false,
        border: false,
        engDescription: "(of the weather) very hot:",
        answer: "scorching",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 205,
        videoFile: video8,
        rusQuestion: "очень горячий",
        before: false,
        border: false,
        engDescription: "extremely hot:",
        answer: "blistering",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 204,
        videoFile: video7,
        rusQuestion: "опасный",
        before: false,
        border: false,
        engDescription: "extremely dangerous:",
        answer: "perilous",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 203,
        videoFile: video6,
        rusQuestion: "просить , искать",
        before: false,
        border: false,
        engDescription: "past simple and past participle of seek (to try to find or get something, especially something that is not a physical object:)",
        answer: "sought",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 202,
        videoFile: video5,
        rusQuestion: "овладевать",
        before: false,
        border: false,
        engDescription: "to become strong; to be established:",
        answer: "take hold",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 201,
        videoFile: video4,
        rusQuestion: "по всему , повсюду",
        before: false,
        border: false,
        engDescription: "in every part, or during the whole period of time:",
        answer: "throughout",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 200,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 199,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 198,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 197,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 196,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 195,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 194,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 193,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 192,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 191,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 190,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 189,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 188,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 187,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 186,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 185,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 184,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 183,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 182,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 181,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 180,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 179,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 178,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 177,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 176,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 175,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 174,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 173,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 172,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 171,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 170,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 169,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 168,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 167,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 166,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 165,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 164,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 163,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 162,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 161,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 160,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 159,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 158,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 157,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 156,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 155,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 154,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 153,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 152,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 151,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 150,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 149,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 148,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 147,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 146,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 145,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 144,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 143,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 142,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 141,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 140,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 139,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 138,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 137,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 136,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 135,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 134,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 133,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 132,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 131,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 130,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 129,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 128,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 127,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 126,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 125,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 124,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 123,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 122,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 121,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 120,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 119,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 118,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 117,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 116,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 115,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 114,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 113,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 112,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 111,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 110,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 109,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 108,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 107,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 106,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 105,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 104,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 103,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 102,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 101,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 100,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 99,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 98,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 97,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 96,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 95,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 94,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 93,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 92,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 91,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 80,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 89,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 88,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 87,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 86,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 85,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 84,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 83,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 82,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 81,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 80,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 79,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 78,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 77,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 76,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 75,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 74,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 73,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 72,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 71,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 70,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 69,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 68,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 67,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 66,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 65,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 64,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 63,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 62,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 61,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 60,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 59,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 58,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 57,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 56,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 55,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 54,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 53,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 52,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 51,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 50,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 49,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 48,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 47,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 46,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 45,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 44,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 43,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 42,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 41,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 40,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 39,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 38,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 37,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 36,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 35,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 34,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 33,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 32,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 31,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 30,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 29,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 28,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 27,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 26,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 25,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 24,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 23,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 22,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 21,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 20,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 19,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 18,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 17,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 16,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 15,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 14,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 13,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 12,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 11,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 10,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 9,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 8,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 7,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 6,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 5,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 4,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 3,
        videoFile: video2,
        rusQuestion: "idu",
        before: false,
        border: false,
        engDescription: "the process of changing your position is space",
        answer: "go",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 2,
        videoFile: video3,
        rusQuestion: "delaiu",
        before: false,
        border: false,
        engDescription: "action in prograss",
        answer: "do",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 1,
        videoFile: video1,
        rusQuestion: "hotschu",
        before: false,
        border: false,
        engDescription: "feeling that expresses desire about having something or wish of doing something.",
        answer: "want",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    }
]
