
import video4 from "../../assets/video4.mp4"
import video5 from "../../assets/video5.mp4"
import video6 from "../../assets/video6.mp4"
import video7 from "../../assets/video7.mp4"
import video8 from "../../assets/video8.mp4"
import video9 from "../../assets/video9.mp4"
import video10 from "../../assets/video10.mp4"
import video11 from "../../assets/video11.mp4"
import video12 from "../../assets/video12.mp4"
import video13 from "../../assets/video13.mp4"
import video14 from "../../assets/video14.mp4"
import video15 from "../../assets/video15.mp4"
import video16 from "../../assets/video16.mp4"
import video17 from "../../assets/video17.mp4"
import video18 from "../../assets/video18.mp4"
import video19 from "../../assets/video19.mp4"
import video20 from "../../assets/video20.mp4"
import video21 from "../../assets/video21.mp4"
import video22 from "../../assets/video22.mp4"
import video23 from "../../assets/video23.mp4"
import video24 from "../../assets/video24.mp4"
import video25 from "../../assets/video25.mp4"
import video26 from "../../assets/video26.mp4"
import video27 from "../../assets/video27.mp4"
import video28 from "../../assets/video28.mp4"
import video29 from "../../assets/video29.mp4"
import video30 from "../../assets/video30.mp4"
import video31 from "../../assets/video31.mp4"
import video32 from "../../assets/video32.mp4"
import video33 from "../../assets/video33.mp4"
import video34 from "../../assets/video34.mp4"
import video35 from "../../assets/video35.mp4"
import video36 from "../../assets/video36.mp4"
import video37 from "../../assets/video37.mp4"
import video38 from "../../assets/video38.mp4"
import video39 from "../../assets/video39.mp4"
import video40 from "../../assets/video40.mp4"
import video41 from "../../assets/video41.mp4"
import video42 from "../../assets/video42.mp4"
import video43 from "../../assets/video43.mp4"
import video44 from "../../assets/video44.mp4"
import video45 from "../../assets/video45.mp4"
import video46 from "../../assets/video46.mp4"
import video47 from "../../assets/video47.mp4"
import video48 from "../../assets/video48.mp4"
import video49 from "../../assets/video49.mp4"
import video50 from "../../assets/video50.mp4"
import video51 from "../../assets/video51.mp4"
import video52 from "../../assets/video52.mp4"
import video53 from "../../assets/video53.mp4"
import video54 from "../../assets/video54.mp4"
import video55 from "../../assets/video55.mp4"
import video56 from "../../assets/video56.mp4"
import video57 from "../../assets/video57.mp4"
import video58 from "../../assets/video58.mp4"
import video59 from "../../assets/video59.mp4"
import video60 from "../../assets/video60.mp4"
import video61 from "../../assets/video61.mp4"
import video62 from "../../assets/video62.mp4"
import video63 from "../../assets/video63.mp4"
import video64 from "../../assets/video64.mp4"
import video65 from "../../assets/video65.mp4"
import video66 from "../../assets/video66.mp4"
import video67 from "../../assets/video67.mp4"
import video68 from "../../assets/video68.mp4"
import video69 from "../../assets/video69.mp4"
import video70 from "../../assets/video70.mp4"
import video71 from "../../assets/video71.mp4"
import video72 from "../../assets/video72.mp4"
import video73 from "../../assets/video73.mp4"
import video74 from "../../assets/video74.mp4"
import video75 from "../../assets/video75.mp4"
import video76 from "../../assets/video76.mp4"
import video77 from "../../assets/video77.mp4"
import video78 from "../../assets/video78.mp4"
import video79 from "../../assets/video79.mp4"
import video80 from "../../assets/video80.mp4"
import video81 from "../../assets/video81.mp4"
import video82 from "../../assets/video82.mp4"
import video83 from "../../assets/video83.mp4"
import video84 from "../../assets/video84.mp4"
import video85 from "../../assets/video85.mp4"
import video86 from "../../assets/video86.mp4"
import video87 from "../../assets/video87.mp4"
import video88 from "../../assets/video88.mp4"
import video89 from "../../assets/video89.mp4"
import video90 from "../../assets/video90.mp4"
import video91 from "../../assets/video91.mp4"
import video92 from "../../assets/video92.mp4"
import video93 from "../../assets/video93.mp4"
import video94 from "../../assets/video94.mp4"
import video95 from "../../assets/video95.mp4"
import video96 from "../../assets/video96.mp4"
import video97 from "../../assets/video97.mp4"
import video98 from "../../assets/video98.mp4"
import video99 from "../../assets/video99.mp4"
import video100 from "../../assets/video100.mp4"
import video101 from "../../assets/video101.mp4"
import video102 from "../../assets/video102.mp4"
import video103 from "../../assets/video103.mp4"
import video104 from "../../assets/video104.mp4"
import video105 from "../../assets/video105.mp4"
import video106 from "../../assets/video106.mp4"
import video107 from "../../assets/video107.mp4"
import video108 from "../../assets/video108.mp4"
import video109 from "../../assets/video109.mp4"
import video110 from "../../assets/video110.mp4"
import video111 from "../../assets/video111.mp4"
import video112 from "../../assets/video112.mp4"
import video113 from "../../assets/video113.mp4"
import video114 from "../../assets/video114.mp4"
import video115 from "../../assets/video115.mp4"
import video116 from "../../assets2_hotelTransilvania/video116.mp4"
import video117 from "../../assets2_hotelTransilvania/video117.mp4"
import video118 from "../../assets2_hotelTransilvania/video118.mp4"
import video119 from "../../assets2_hotelTransilvania/video119.mp4"
import video120 from "../../assets2_hotelTransilvania/video120.mp4"
import video121 from "../../assets2_hotelTransilvania/video121.mp4"
import video122 from "../../assets2_hotelTransilvania/video122.mp4"
import video123 from "../../assets2_hotelTransilvania/video123.mp4"
import video124 from "../../assets2_hotelTransilvania/video124.mp4"
import video125 from "../../assets2_hotelTransilvania/video125.mp4"
import video126 from "../../assets2_hotelTransilvania/video126.mp4"
import video127 from "../../assets2_hotelTransilvania/video127.mp4"
import video128 from "../../assets2_hotelTransilvania/video128.mp4"
import video129 from "../../assets2_hotelTransilvania/video129.mp4"
import video130 from "../../assets2_hotelTransilvania/video130.mp4"
import video131 from "../../assets2_hotelTransilvania/video131.mp4"
import video132 from "../../assets2_hotelTransilvania/video132.mp4"
import video133 from "../../assets2_hotelTransilvania/video133.mp4"
import video134 from "../../assets2_hotelTransilvania/video134.mp4"
import video135 from "../../assets2_hotelTransilvania/video135.mp4"
import video136 from "../../assets2_hotelTransilvania/video136.mp4"
import video137 from "../../assets2_hotelTransilvania/video137.mp4"
import video138 from "../../assets2_hotelTransilvania/video138.mp4"
import video139 from "../../assets2_hotelTransilvania/video139.mp4"
import video140 from "../../assets2_hotelTransilvania/video140.mp4"



 export const new_data = [
    {
        id: 340,
        videoFile: video131,
        rusQuestion: "ущипнул меня",
        before: false,
        border: false,
        engDescription: "to press something, especially someone's skin, strongly between two hard things such as a finger and a thumb, usually causing pain:",
        answer: "pinched me",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 339,
        videoFile: video130,
        rusQuestion: "домоводство",
        before: false,
        border: false,
        engDescription: "the activity of taking care of a house, esp. by cleaning it:",
        answer: "housekeeping",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 338,
        videoFile: video129,
        rusQuestion: "грязь",
        before: false,
        border: false,
        engDescription: "thick, unpleasant dirt:",
        answer: "filth",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 337,
        videoFile: video128,
        rusQuestion: "кладбище",
        before: false,
        border: false,
        engDescription: "an area of ground in which dead bodies are buried",
        answer: "cemetery",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 336,
        videoFile: video127,
        rusQuestion: "наматывать",
        before: false,
        border: false,
        engDescription: "to get control of something or someone, sometimes by offering something in exchange:",
        answer: "reel in",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 335,
        videoFile: video126,
        rusQuestion: "забитый",
        before: false,
        border: false,
        engDescription: "blocked or filled with something:",
        answer: "clogged",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 334,
        videoFile: video125,
        rusQuestion: "сантехника",
        before: false,
        border: false,
        engDescription: "the water pipes and similar systems in a building:",
        answer: "plumbing",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 333,
        videoFile: video124,
        rusQuestion: "феерия",
        before: false,
        border: false,
        engDescription: "a large, exciting, and expensive event or entertainment:",
        answer: "extravaganza",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 332,
        videoFile: video123,
        rusQuestion: "путеводитель",
        before: false,
        border: false,
        engDescription: "a detailed plan or route of a journey:",
        answer: "itinerary",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 331,
        videoFile: video122,
        rusQuestion: "костер",
        before: false,
        border: false,
        engDescription: "a large fire that is made outside to burn unwanted things, or for pleasure",
        answer: "bonfire",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 330,
        videoFile: video120,
        rusQuestion: "согните ноги и оттолкнитесь",
        before: false,
        border: false,
        engDescription: "согните ноги и оттолкнитесь",
        answer: "bend the legs and push off",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 329,
        videoFile: video119,
        rusQuestion: "какашки",
        before: false,
        border: false,
        engDescription: " a solid waste from the body:",
        answer: "poop",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 328,
        videoFile: video118,
        rusQuestion: "квадратные метры",
        before: false,
        border: false,
        engDescription: "the amount of flat space that covers an area",
        answer: "square footage",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 327,
        videoFile: video117,
        rusQuestion: "задницу",
        before: false,
        border: false,
        engDescription: "the part of your body that you sit on; bottom:",
        answer: "tush",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    }, 
    {
        id: 326,
        videoFile: video116,
        rusQuestion: "испугать",
        before: false,
        border: false,
        engDescription: "to do something unexpected that surprises and sometimes worries a person or animal:",
        answer: "startle",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    }, 
   {
        id: 325,
        videoFile: video115,
        rusQuestion: "она тебя утомит",
        before: false,
        border: false,
        engDescription: "to make someone extremely tired:",
        answer: "wear you out",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 324,
        videoFile: video114,
        rusQuestion: "ощущение",
        before: false,
        border: false,
        engDescription: "the ability to feel something physically, especially by touching, or a physical feeling that results from this ability:",
        answer: "sensation",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 323,
        videoFile: video113,
        rusQuestion: "предчувствие",
        before: false,
        border: false,
        engDescription: "a feeling that something, especially something unpleasant, is going to happen:",
        answer: "premonition",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 322,
        videoFile: video112,
        rusQuestion: "суеверие",
        before: false,
        border: false,
        engDescription: "belief that is not based on human reason or scientific knowledge, but is connected with old ideas about magic, etc.:",
        answer: "superstition",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 321,
        videoFile: video111,
        rusQuestion: "бородавки и все такое",
        before: false,
        border: false,
        engDescription: "describing or including all the bad qualities in a person's character, with no attempt to hide them:",
        answer: "warts and all",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 320,
        videoFile: video110,
        rusQuestion: "квакать",
        before: false,
        border: false,
        engDescription: "When animals such as frogs and crows ooooo, they make deep rough sounds.",
        answer: "croak",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 319,
        videoFile: video109,
        rusQuestion: "пена",
        before: false,
        border: false,
        engDescription: "a mass of very small bubbles formed on the surface of a liquid",
        answer: "foam",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 318,
        videoFile: video108,
        rusQuestion: "ворочаюсь",
        before: false,
        border: false,
        engDescription: "to move about from side to side or turn a lot in bed, especially because you cannot sleep:",
        answer: "toss and turn",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 317,
        videoFile: video106,
        rusQuestion: "уличный",
        before: false,
        border: false,
        engDescription: "able to deal successfully with dangerous or difficult situations in big towns or cities where there is a lot of crime:",
        answer: "streetwise",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 316,
        videoFile: video107,
        rusQuestion: "шансы",
        before: false,
        border: false,
        engDescription: "the probability (= how likely it is) that a particular thing will or will not happen:",
        answer: "odds",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 315,
        videoFile: video105,
        rusQuestion: "выпечка",
        before: false,
        border: false,
        engDescription: "a food made from a mixture of flour, fat, and water, rolled flat and either wrapped around or put over or under other foods, and then baked:",
        answer: "pastry",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 314,
        videoFile: video104,
        rusQuestion: "ров",
        before: false,
        border: false,
        engDescription: "a long, wide hole that is dug all the way around a place such as a castle and usually filled with water, to make it more difficult to attack",
        answer: "moat",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 313,
        videoFile: video103,
        rusQuestion: "перемотать назад",
        before: false,
        border: false,
        engDescription: "to make a recording go back towards the beginning:",
        answer: "rewind",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 312,
        videoFile: video102,
        rusQuestion: "все прояснить",
        before: false,
        border: false,
        engDescription: "to allow a secret to be known, usually without intending to:",
        answer: "let the cat out of the bag",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 311,
        videoFile: video101,
        rusQuestion: "сумасброд",
        before: false,
        border: false,
        engDescription: "silly and often amusing:  used to describe silly and funny behaviour or a plan that is very silly and funny and unlikely to succeed:",
        answer: "madcap",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 310,
        videoFile: video100,
        rusQuestion: "полудикая лошадь",
        before: false,
        border: false,
        engDescription: "a wild horse of the western US",
        answer: "bronco",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 309,
        videoFile: video99,
        rusQuestion: "Позволю себе не согласиться",
        before: false,
        border: false,
        engDescription: "a way of saying ...I do not agree... that is polite, but may sound unfriendly",
        answer: "I beg to differ",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 308,
        videoFile: video98,
        rusQuestion: "отозвать",
        before: false,
        border: false,
        engDescription: "to decide that a planned event, especially a sports event, will not happen, or to end an activity because it is no longer useful or possible:",
        answer: "to call off",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 307,
        videoFile: video97,
        rusQuestion: "резной",
        before: false,
        border: false,
        engDescription: "to make something by cutting into especially wood or stone, or to cut into the surface of stone, wood, etc.:",
        answer: "carved",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 306,
        videoFile: video96,
        rusQuestion: "голубь , простофиля",
        before: false,
        border: false,
        engDescription: "a large, usually gray-and-white bird that lives esp. in cities:",
        answer: "pigeon",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 305,
        videoFile: video95,
        rusQuestion: "тупик",
        before: false,
        border: false,
        engDescription: "a road that is closed at one end, and does not lead anywhere:",
        answer: "dead end",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 304,
        videoFile: video94,
        rusQuestion: "возмещать",
        before: false,
        border: false,
        engDescription: "to pay back or to reward someone or something:",
        answer: "repay",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 303,
        videoFile: video93,
        rusQuestion: "парик",
        before: false,
        border: false,
        engDescription: "a covering of artificial hair worn on the head to hide a loss of hair or to cover your own hair:",
        answer: "wig",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 302,
        videoFile: video92,
        rusQuestion: "сварливый",
        before: false,
        border: false,
        engDescription: "arguing and complaining a lot:",
        answer: "cantankerous",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 301,
        videoFile: video91,
        rusQuestion: "рысью",
        before: false,
        border: false,
        engDescription: "If a horse or similar animal with four legs oooooo, it runs at its slowest speed, using short steps in which a front leg and the back leg on the opposite side move together:",
        answer: "trotting",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 300,
        videoFile: video90,
        rusQuestion: "ржал",
        before: false,
        border: false,
        engDescription: "(of a horse) to make a soft, high sound:",
        answer: "whinny",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 299,
        videoFile: video90,
        rusQuestion: "жеребец",
        before: false,
        border: false,
        engDescription: "an adult male horse that is used for breeding",
        answer: "stallion",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 298,
        videoFile: video89,
        rusQuestion: "ягодицы",
        before: false,
        border: false,
        engDescription: "either side of a person's bottom",
        answer: "buttocks",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 297,
        videoFile: video89,
        rusQuestion: "упругий , тугой",
        before: false,
        border: false,
        engDescription: "tight or completely stretched:",
        answer: "taut",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 296,
        videoFile: video88,
        rusQuestion: "волосы",
        before: false,
        border: false,
        engDescription: "the hair on someone's head:",
        answer: "locks",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 295,
        videoFile: video88,
        rusQuestion: "волнистый",
        before: false,
        border: false,
        engDescription: "having a series of curves:",
        answer: "wavy",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 294,
        videoFile: video87,
        rusQuestion: "поставь свой последний доллар",
        before: false,
        border: false,
        engDescription: "used to say that you are completely certain that something is true or will happen:",
        answer: "bet your bottom",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 293,
        videoFile: video86,
        rusQuestion: "ударить , прикончить",
        before: false,
        border: false,
        engDescription: "to give someone or something a hard, noisy hit:  to hit someone or something noisily:",
        answer: "whack",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 292,
        videoFile: video86,
        rusQuestion: "подлый",
        before: false,
        border: false,
        engDescription: "dirty, cheap, or not socially acceptable, especially relating to moral or sexual matters:",
        answer: "sleazy",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 291,
        videoFile: video85,
        rusQuestion: "недействительный , подделка",
        before: false,
        border: false,
        engDescription: "something that has no value or that does not work:",
        answer: "dud",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 290,
        videoFile: video84,
        rusQuestion: "валяться",
        before: false,
        border: false,
        engDescription: "(especially of some animals) to lie or roll around slowly in deep, wet earth, sand, or water:",
        answer: "wallowing",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 289,
        videoFile: video83,
        rusQuestion: "за нас",
        before: false,
        border: false,
        engDescription: "said when asking a group of people to hold up their glasses and then drink as an expression of good wishes to someone or hope for the success of something:",
        answer: "here's to us",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 288,
        videoFile: video82,
        rusQuestion: "глоток",
        before: false,
        border: false,
        engDescription: "to drink, taking only a very small amount at a time:",
        answer: "sip",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 287,
        videoFile: video81,
        rusQuestion: "мазать",
        before: false,
        border: false,
        engDescription: "to spread a liquid or a thick substance over a surface:",
        answer: "smear",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 286,
        videoFile: video80,
        rusQuestion: "покалывание",
        before: false,
        border: false,
        engDescription: "in a way that causes a feeling as if a lot of sharp points are being put quickly and lightly into your body:",
        answer: "tingling",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 285,
        videoFile: video79,
        rusQuestion: "сожалею об этом дне",
        before: false,
        border: false,
        engDescription: "to feel very sorry about an event:",
        answer: "rue the day",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 284,
        videoFile: video78,
        rusQuestion: "поразить",
        before: false,
        border: false,
        engDescription: "to hit someone forcefully or to have a sudden powerful or damaging effect on someone",
        answer: "smite",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 283,
        videoFile: video78,
        rusQuestion: "отрывать",
        before: false,
        border: false,
        engDescription: "to tear or break something violently:",
        answer: "rend",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 282,
        videoFile: video77,
        rusQuestion: "тыква",
        before: false,
        border: false,
        engDescription: "a large, round vegetable with hard, yellow or orange flesh:",
        answer: "pumpkin",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 281,
        videoFile: video76,
        rusQuestion: "залитый",
        before: false,
        border: false,
        engDescription: "to cover most or all of a surface: To ooooo someone is to kill someone by covering the person’s face, making it impossible to breathe.",
        answer: "smothered",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 280,
        videoFile: video76,
        rusQuestion: "жареный",
        before: false,
        border: false,
        engDescription: "cooked in hot oil or fat:",
        answer: "fried",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 279,
        videoFile: video75,
        rusQuestion: "заваруха",
        before: false,
        border: false,
        engDescription: "a sudden, short period of noise, confusion, or excited movement:",
        answer: "commotion",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 278,
        videoFile: video74,
        rusQuestion: "отвергать",
        before: false,
        border: false,
        engDescription: "to refuse to accept something or someone because you feel that thing or person is not worth having:",
        answer: "spurn",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 277,
        videoFile: video73,
        rusQuestion: "почитаемый",
        before: false,
        border: false,
        engDescription: "to very much respect and admire someone or something:",
        answer: "revered",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 276,
        videoFile: video72,
        rusQuestion: "супружеский",
        before: false,
        border: false,
        engDescription: "connected with marriage:",
        answer: "marital",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 275,
        videoFile: video71,
        rusQuestion: "смягчитель",
        before: false,
        border: false,
        engDescription: "a substance used to make something soft:",
        answer: "softener",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 274,
        videoFile: video71,
        rusQuestion: "поганка",
        before: false,
        border: false,
        engDescription: "a poisonous fungus with a round top and a narrow stem",
        answer: "toadstool",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 273,
        videoFile: video70,
        rusQuestion: "сглаз",
        before: false,
        border: false,
        engDescription: "a magical spell or power that causes someone to have a difficult or unpleasant time:",
        answer: "whammy",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 272,
        videoFile: video69,
        rusQuestion: "злой",
        before: false,
        border: false,
        engDescription: "morally wrong and bad:",
        answer: "wicked",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 271,
        videoFile: video68,
        rusQuestion: "ты спятил?",
        before: false,
        border: false,
        engDescription: "to be very silly or stupid:",
        answer: "off your nut",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 270,
        videoFile: video67,
        rusQuestion: "вор-взломщик",
        before: false,
        border: false,
        engDescription: "a person who illegally enters buildings and steals things",
        answer: "burglar",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 269,
        videoFile: video66,
        rusQuestion: "придумывание",
        before: false,
        border: false,
        engDescription: "to make something, usually food, by adding several different parts together, often in a way that is original or not planned: also to make something new from different things:",
        answer: "concocting",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 268,
        videoFile: video65,
        rusQuestion: "обувь",
        before: false,
        border: false,
        engDescription: "shoes, boots, or any other outer covering for the human foot:",
        answer: "footwear",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 267,
        videoFile: video64,
        rusQuestion: "похоть , страсть",
        before: false,
        border: false,
        engDescription: "a very strong sexual desire:",
        answer: "lust",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 266,
        videoFile: video63,
        rusQuestion: "капля",
        before: false,
        border: false,
        engDescription: "a small round-shaped amount of liquid:",
        answer: "drop",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 265,
        videoFile: video62,
        rusQuestion: "щепотка",
        before: false,
        border: false,
        engDescription: "a small amount of something, such as a powder, especially the amount that a person can hold between their first finger and thumb:",
        answer: "pinch",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 264,
        videoFile: video61,
        rusQuestion: "капризный",
        before: false,
        border: false,
        engDescription: "When children are oooooo, or their behaviour is oooooo, they behave badly or do not do what they are told to do:",
        answer: "naughty",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 263,
        videoFile: video60,
        rusQuestion: "угнетенный",
        before: false,
        border: false,
        engDescription: "governed in an unfair and cruel way and prevented from having opportunities and freedom:",
        answer: "oppressed",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 262,
        videoFile: video60,
        rusQuestion: "униженный",
        before: false,
        border: false,
        engDescription: "to cause people to feel that they or other people have no value and do not have the respect or good opinion of others:",
        answer: "degraded",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 261,
        videoFile: video59,
        rusQuestion: "союз",
        before: false,
        border: false,
        engDescription: "an organization that represents the people who work in a particular industry, protects their rights and may agree pay, working conditions, etc. with their employers:",
        answer: "union",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 260,
        videoFile: video58,
        rusQuestion: "зайти , заглянуть",
        before: false,
        border: false,
        engDescription: "to visit briefly:",
        answer: "pop in",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 259,
        videoFile: video57,
        rusQuestion: "зелья",
        before: false,
        border: false,
        engDescription: "a liquid that is believed to have a magical effect on someone who drinks it:",
        answer: "potion",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 258,
        videoFile: video57,
        rusQuestion: "заклинания",
        before: false,
        border: false,
        engDescription: "an evil spell, bringing bad luck and trouble:",
        answer: "hex",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 257,
        videoFile: video56,
        rusQuestion: "изба",
        before: false,
        border: false,
        engDescription: "a small house, usually in the countryside:",
        answer: "cottage",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 256,
        videoFile: video55,
        rusQuestion: "выкатить приветственный вагон",
        before: false,
        border: false,
        engDescription: "used to refer to a happy and friendly way of greeting people who are new to a place:",
        answer: "roll out the welcome wagon",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 255,
        videoFile: video54,
        rusQuestion: "изысканный",
        before: false,
        border: false,
        engDescription: "very beautiful and delicate: especially beautiful or admirable:",
        answer: "exquisite",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 254,
        videoFile: video54,
        rusQuestion: "блюдо",
        before: false,
        border: false,
        engDescription: "food prepared in a particular way as part of a meal:  a container, flatter than a bowl and sometimes with a lid, from which food can be served or which can be used for cooking:",
        answer: "dish",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 253,
        videoFile: video53,
        rusQuestion: "праздничный",
        before: false,
        border: false,
        engDescription: "having or producing happy and enjoyable feelings suitable for a festival or other special occasion:",
        answer: "festive",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 252,
        videoFile: video52,
        rusQuestion: "расслабляться",
        before: false,
        border: false,
        engDescription: "to become more relaxed and less serious:",
        answer: "lighten up",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 251,
        videoFile: video51,
        rusQuestion: "пощажен",
        before: false,
        border: false,
        engDescription: "If something is ooooo, it is available to use because it is extra: to not hurt or destroy something or someone:",
        answer: "spared",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 250,
        videoFile: video50,
        rusQuestion: "обязан",
        before: false,
        border: false,
        engDescription: "to be forced to do something or feel that you must do something:",
        answer: "obliged",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 249,
        videoFile: video50,
        rusQuestion: "сопровождать",
        before: false,
        border: false,
        engDescription: "to go with someone or to be provided or exist at the same time as something:  to go with someone or to exist at the same time as something:",
        answer: "accompany",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 248,
        videoFile: video49,
        rusQuestion: "неправильно судить",
        before: false,
        border: false,
        engDescription: "to form an opinion or idea about someone or something that is unfair or wrong:",
        answer: "misjudge",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 247,
        videoFile: video48,
        rusQuestion: "бобы",
        before: false,
        border: false,
        engDescription: "a seed, or the pod containing seeds, of various climbing plants, eaten as a vegetable:",
        answer: "beans",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 246,
        videoFile: video47,
        rusQuestion: "помет",
        before: false,
        border: false,
        engDescription: "a group of animals that are born at the same time and have the same mother:   small pieces of rubbish that have been left lying on the ground in public places:",
        answer: "litter",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 245,
        videoFile: video46,
        rusQuestion: "умолять",
        before: false,
        border: false,
        engDescription: "to ask someone to do or not do something in a very sincere, emotional, and determined way:",
        answer: "implore",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 244,
        videoFile: video45,
        rusQuestion: "кастрировать",
        before: false,
        border: false,
        engDescription: "to remove part of an animal's sexual organs, so that it cannot produce young animals:",
        answer: "neuter",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 243,
        videoFile: video44,
        rusQuestion: "орудие",
        before: false,
        border: false,
        engDescription: "a gun: or weapon:",
        answer: "piece",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 242,
        videoFile: video43,
        rusQuestion: "мурлыкать",
        before: false,
        border: false,
        engDescription: "to make a quiet, continuous, soft sound:  (of a cat) to make a soft, low, continuous sound",
        answer: "purr",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 241,
        videoFile: video42,
        rusQuestion: "связь , узы",
        before: false,
        border: false,
        engDescription: "to develop a close connection or strong relationship with someone, or to make someone do this:  to stick materials together, especially using glue, or to be stuck together like this:  a close connection joining two or more people:",
        answer: "bond",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 240,
        videoFile: video41,
        rusQuestion: "обидчивый",
        before: false,
        border: false,
        engDescription: "angry and offended:",
        answer: "huffy",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 239,
        videoFile: video40,
        rusQuestion: "зловещий",
        before: false,
        border: false,
        engDescription: "making you feel that something bad or evil might happen:  evil, or suggesting that something evil is going to happen:",
        answer: "sinister",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 238,
        videoFile: video39,
        rusQuestion: "подлый , презренный",
        before: false,
        border: false,
        engDescription: "very unpleasant or bad, causing strong feelings of dislike:",
        answer: "despicable",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 237,
        videoFile: video38,
        rusQuestion: "пижамную вечеринку",
        before: false,
        border: false,
        engDescription: "a party when a group of children spend the night at one child's house",
        answer: "slumber party",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 236,
        videoFile: video37,
        rusQuestion: "подсказать тебе",
        before: false,
        border: false,
        engDescription: "to give someone information that is necessary or new:",
        answer: "clue you in",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 235,
        videoFile: video36,
        rusQuestion: "майонез",
        before: false,
        border: false,
        engDescription: "informal for mayonnaise :",
        answer: "mayo",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 234,
        videoFile: video35,
        rusQuestion: "сонный",
        before: false,
        border: false,
        engDescription: "being in a state between sleeping and being awake:",
        answer: "drowsy",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 233,
        videoFile: video34,
        rusQuestion: "гладкий",
        before: false,
        border: false,
        engDescription: "to make something perfectly flat or regular: having a surface or consisting of a substance that is perfectly regular and has no holes, lumps, or areas that rise or fall suddenly:",
        answer: "smooth",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 232,
        videoFile: video33,
        rusQuestion: "туфли-лодочки",
        before: false,
        border: false,
        engDescription: "a type of flat shoe, like a ballet dancer's shoe, worn by women",
        answer: "pumps",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 231,
        videoFile: video32,
        rusQuestion: "легким движением запястья , резкое движение",
        before: false,
        border: false,
        engDescription: "a song by the British rock band Queen",
        answer: "flick of the wrist",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 230,
        videoFile: video31,
        rusQuestion: "палочка",
        before: false,
        border: false,
        engDescription: "a special thin stick waved by a person who is performing magic tricks:",
        answer: "wand",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 229,
        videoFile: video30,
        rusQuestion: "сладкий горох",
        before: false,
        border: false,
        engDescription: "a climbing plant with sweet-smelling flowers that are often a pale colour",
        answer: "sweet pea",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 228,
        videoFile: video29,
        rusQuestion: "лекарство",
        before: false,
        border: false,
        engDescription: "a successful way of curing an illness or dealing with a problem or difficulty:",
        answer: "remedy",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 227,
        videoFile: video28,
        rusQuestion: "животики",
        before: false,
        border: false,
        engDescription: "the stomach, or the lower front part of the body:",
        answer: "tummies",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 226,
        videoFile: video27,
        rusQuestion: "очарованный",
        before: false,
        border: false,
        engDescription: "affected by magic or seeming to be affected by magic:",
        answer: "enchanted",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
     {
        id: 225,
        videoFile: video26,
        rusQuestion: "чертовски",
        before: false,
        border: false,
        engDescription: "used instead of damn to express anger:",
        answer: "darn",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 224,
        videoFile: video25,
        rusQuestion: "бортовое",
        before: false,
        border: false,
        engDescription: "happening or available during a flight:",
        answer: "in-flight",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 223,
        videoFile: video24,
        rusQuestion: "незрелый",
        before: false,
        border: false,
        engDescription: "not behaving in a way that is as calm and wise as people expect from someone of your age:",
        answer: "immature",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 222,
        videoFile: video23,
        rusQuestion: "попасть в пробку",
        before: false,
        border: false,
        engDescription: "the expression means that in the course of your journey you encountered congestion and delays as the road was very busy with other road users.",
        answer: "hit traffic",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 221,
        videoFile: video22,
        rusQuestion: "Для тебя есть мелкий шрифт",
        before: false,
        border: false,
        engDescription: "The term usually refers to the small text in contracts that people typically sign when signing up for something",
        answer: "there's some fine print for you",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 220,
        videoFile: video21,
        rusQuestion: "напыщенный",
        before: false,
        border: false,
        engDescription: "too serious and full of importance: feeling or showing that you think you are better or more important than other people:",
        answer: "pompous",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 219,
        videoFile: video20,
        rusQuestion: "Загородный клуб",
        before: false,
        border: false,
        engDescription: "a sports or social organization based in the countryside, often one that only allows people to become members if they have enough money or a high social position",
        answer: "country club",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 218,
        videoFile: video19,
        rusQuestion: "он же",
        before: false,
        border: false,
        engDescription: "abbreviation for also known as: used when someone has another name:",
        answer: "aka",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 217,
        videoFile: video19,
        rusQuestion: "он же",
        before: false,
        border: false,
        engDescription: "abbreviation for also known as: used when someone has another name:",
        answer: "aka",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 216,
        videoFile: video18,
        rusQuestion: "бал",
        before: false,
        border: false,
        engDescription: "a large, formal occasion where people dance",
        answer: "ball",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 215,
        videoFile: video17,
        rusQuestion: "настоящим , сим",
        before: false,
        border: false,
        engDescription: "with these words or with this action:  by this statement, action, or law:",
        answer: "hereby",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 214,
        videoFile: video17,
        rusQuestion: "вызванный",
        before: false,
        border: false,
        engDescription: "an official demand to appear in a court of law:   an order to come and see someone:  to order someone to come to a person or place:",
        answer: "summoned",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 213,
        videoFile: video16,
        rusQuestion: "подлый , мошеннически",
        before: false,
        border: false,
        engDescription: "used to describe people or behaviour that you disapprove of but still like:",
        answer: "rascally",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 212,
        videoFile: video15,
        rusQuestion: "приятное зрелище, больной , болячка , Взгляд усталых глаз",
        before: false,
        border: false,
        engDescription: "a way of saying that you are very pleased to see someone or that you think someone is very attractive:",
        answer: "a sight for sore eyes",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 211,
        videoFile: video14,
        rusQuestion: "петь",
        before: false,
        border: false,
        engDescription: "to sing or play a musical instrument very loudly:",
        answer: "belting out",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 210,
        videoFile: video13,
        rusQuestion: "излечивать",
        before: false,
        border: false,
        engDescription: "to make someone with an illness healthy again:",
        answer: "cure",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 209,
        videoFile: video12,
        rusQuestion: "паутинка",
        before: false,
        border: false,
        engDescription: "the very thin thread that spiders produce to make webs",
        answer: "gossamer",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 208,
        videoFile: video11,
        rusQuestion: "страшное",
        before: false,
        border: false,
        engDescription: "causing fear or worry:",
        answer: "dreaded",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 207,
        videoFile: video10,
        rusQuestion: "конечность",
        before: false,
        border: false,
        engDescription: "an arm or leg of a person or animal:",
        answer: "limb",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 206,
        videoFile: video9,
        rusQuestion: "палящий , обжигающий",
        before: false,
        border: false,
        engDescription: "(of the weather) very hot:",
        answer: "scorching",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 205,
        videoFile: video8,
        rusQuestion: "очень горячий",
        before: false,
        border: false,
        engDescription: "extremely hot:",
        answer: "blistering",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 204,
        videoFile: video7,
        rusQuestion: "опасный",
        before: false,
        border: false,
        engDescription: "extremely dangerous:",
        answer: "perilous",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 203,
        videoFile: video6,
        rusQuestion: "просить , искать",
        before: false,
        border: false,
        engDescription: "past simple and past participle of seek (to try to find or get something, especially something that is not a physical object:)",
        answer: "sought",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 202,
        videoFile: video5,
        rusQuestion: "овладевать",
        before: false,
        border: false,
        engDescription: "to become strong; to be established:",
        answer: "take hold",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 201,
        videoFile: video4,
        rusQuestion: "по всему , повсюду",
        before: false,
        border: false,
        engDescription: "in every part, or during the whole period of time:",
        answer: "throughout",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    }
    
       
]

const spare_data = [
    {
        id: 351,
        videoFile: video121,
        rusQuestion: "лес с привидениями",
        before: false,
        border: false,
        engDescription: "building or other place  where a ghost regularly appears.",
        answer: "haunted forest",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 350,
        videoFile: video140,
        rusQuestion: "злодей",
        before: false,
        border: false,
        engDescription: "a bad person who harms other people or breaks the law:",
        answer: "villain",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 349,
        videoFile: video139,
        rusQuestion: "чтобы озадачить нас",
        before: false,
        border: false,
        engDescription: "not familiar, or difficult to understand; different:",
        answer: "to strange us",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 348,
        videoFile: video138,
        rusQuestion: "одолеть",
        before: false,
        border: false,
        engDescription: "to defeat someone by having greater strength or power:",
        answer: "overpower",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 347,
        videoFile: video138,
        rusQuestion: "одолеть",
        before: false,
        border: false,
        engDescription: "to defeat someone by having greater strength or power:",
        answer: "overpower",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 346,
        videoFile: video137,
        rusQuestion: "обнаружил",
        before: false,
        border: false,
        engDescription: "to discover something secret or hidden :",
        answer: "has uncovered",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 345,
        videoFile: video136,
        rusQuestion: "наблюдение",
        before: false,
        border: false,
        engDescription: "the careful watching of a person or place, especially by the police or army, because of a crime that has happened or is expected:",
        answer: "surveillance",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 344,
        videoFile: video135,
        rusQuestion: "убежище",
        before: false,
        border: false,
        engDescription: "(a place that gives) protection or shelter from danger, trouble, unhappiness, etc.:",
        answer: "refuge",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 343,
        videoFile: video134,
        rusQuestion: "вне опасности",
        before: false,
        border: false,
        engDescription: "no longer in difficulty or trouble. out of danger; free from obligation or guilt",
        answer: "off the hook",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 342,
        videoFile: video133,
        rusQuestion: "он всегда действует на полную катушку...наклон...",
        before: false,
        border: false,
        engDescription: "..... means at maximum speed or intensity. ,,,,,, in this context, means to act, behave, or perform.  The idea is that he brings to the engagement a readiness to do something (party, probably) with full intensity.",
        answer: "he always bringing it full tilt",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
    {
        id: 341,
        videoFile: video132,
        rusQuestion: "неотразимый",
        before: false,
        border: false,
        engDescription: "impossible to refuse, oppose, or avoid because it is too pleasant, attractive, or strong:",
        answer: "irresistible",
        myAnswer: "",
        color: "rgb(43, 198, 226)",
    },
   
    
   
    
]
